modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/Raided/issues"
license="MIT"

[[mods]]
modId="raided"
version="${file.jarVersion}"
displayName="Raided"
displayURL="https://www.curseforge.com/minecraft/mc-mods/raided"
authors="Mrbysco, silentine"
description='''
Expands upon the vanilla raid system to allow for more advanced raid mechanics.
'''
[[dependencies.raided]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"